- name: Install ruby by rbenv
  shell: rbenv install {% item.option %} {% item.version %} creates=~/.rbenv/versions/{% item.version %}
  with_items:
    - {version: "2.6.5", option: ""}
    - {version: "2.7.0", option: ""}
  when: not {% travis_build_skip|bool %}

- name: Install gem packages
  become: yes
  gem: name={% item.name %} state={% item.state %} user_install=no
  with_items:
      - {name: "rake", state: "present"}
      - {name: "serverspec", state: "present"}
