- name: Install python from homebrew
  homebrew: name={{ item.name }} state={{ item.state }}
  with_items:
      - {name: "python@3.9", state: "present"}
      - {name: "python@3.8", state: "present"}
      - {name: "pyenv", state: "present"}

- name: Install PyPI packages
  pip: name={{ item.name }}
  with_items:
      - {name: "virtualenv"}
      - {name: "virtualenvwrapper"}
      - {name: "pipenv"}
