- name: Install python from hombrew
  homebrew: name={{ item.name }} state={{ item.state }}
  with_items:
      - {name: "python", state: "present"}
      - {name: "python2", state: "present"}

- name: Install PyPI packages
  pip: name={{ item.name }}
  with_items:
      - {name: "virtualenv"}
      - {name: "virtualenvwrapper"}
      - {name: "mercurial"}
