- name: Install homebrew
  command: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" creates=/usr/local/bin/brew

# - name: Setup homebrew cask
#  homebrew_tap: tap={{ item.tap }} state={{ item.state }}
#  with_items:
#      - {tap: "homebrew/cask-cask", state: "present"}

# - name: Install homebrew cask
#  homebrew: name=cask state=present

- name: Update homebrew
  homebrew: update_homebrew={{ homebrew_update }} upgrade_all={{ homebrew_upgrade_all }}

- name: Upgrade homebrew cask
  homebrew: name=cask state=latest
  when: homebrew_update == "yes"

- name: Cleanup homebrew
  shell: brew cleanup
  when: homebrew_update == "yes"

- name: Install basic packages
  homebrew: name={{ item.name }} state={{ item.state }}
  with_items:
      - {name: "gnu-tar", state: "present"}
      - {name: "ack", state: "present"}
      - {name: "findutils", state: "present"}
      - {name: "readline", state: "present"}
      - {name: "openssl", state: "present"}
      - {name: "gdbm", state: "present"}
      - {name: "sqlite", state: "present"}
      - {name: "autoconf", state: "present"}
      - {name: "git", state: "present"}
      - {name: "hub", state: "present"}
      - {name: "ruby-build", state: "present"}
      - {name: "rbenv", state: "present"}
      - {name: "rbenv-default-gems", state: "present"}
      - {name: "vim", state: "present"}
      - {name: "luajit", state: "present"}
      #- {name: "zsh", state: "present"}
      - {name: "lua", state: "present"}
      - {name: "postgresql", state: "present"}
      - {name: "fontforge", state: "present"}
      - {name: "mariadb", state: "present"}
      - {name: "mysql-connector-c", state: "present"}
      - {name: "exa", state: "present" }
      - {name: "bat", state: "present" }
      - {name: "fd", state: "present" }
      - {name: "ripgrep", state: "present" }
      - {name: "procs", state: "present" }
      - {name: "tmux", state: "present" }
      - {name: "lazydocker", state: "present" }
      - {name: "lazygit", state: "present" }
      - {name: "tig", state: "present" }
      - {name: "nmap", state: "present" }
      - {name: "github/gh/gh", state: "present" }
      - {name: "gtk+3", state: "present" }


